name = "OutlierDetectionInterface"
uuid = "1722ece6-f894-4ffc-b6be-6ca1174e2011"
authors = ["David Muhr <muhrdavid@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1"
